// auto-generated by storage-refresh.sh — do not edit by hand
window.STORAGE = {
  updated: "15:51:42",
  mac:    { pct: 95, used: "188Gi", free: "10Gi", total: "228Gi", ok: true },
  fedora: { pct: 37, used: "86G", free: "149G", total: "236G", ok: true }
};
