#!/bin/zsh
# Writes storage-data.js for upload-dashboard.html — Mac (local df) + Fedora (ssh df).
# Run on a 2-min schedule via launchd (com.cashie.storage-refresh).
set -u
OUT="/Users/cashie/PROJECTS/cashie-portfolio/storage-data.js"

# ---- Mac (local) ----
read -r _ MTOTAL MUSED MAVAIL MCAP _ <<<"$(df -h /System/Volumes/Data | tail -1)"
MPCT="${MCAP%\%}"

# ---- Fedora (ssh, key auth, short timeout) ----
FED=$(timeout 8 ssh -o BatchMode=yes -o ConnectTimeout=5 fedora "df -h / | tail -1" 2>/dev/null)
if [[ -n "$FED" ]]; then
  read -r _ FTOTAL FUSED FAVAIL FCAP _ <<<"$FED"
  FPCT="${FCAP%\%}"
  FOK="true"
else
  FTOTAL="—"; FUSED="—"; FAVAIL="—"; FPCT="0"; FOK="false"
fi

NOW=$(date "+%H:%M:%S")

cat > "$OUT" <<EOF
// auto-generated by storage-refresh.sh — do not edit by hand
window.STORAGE = {
  updated: "${NOW}",
  mac:    { pct: ${MPCT:-0}, used: "${MUSED}", free: "${MAVAIL}", total: "${MTOTAL}", ok: true },
  fedora: { pct: ${FPCT:-0}, used: "${FUSED}", free: "${FAVAIL}", total: "${FTOTAL}", ok: ${FOK} }
};
EOF
